from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch
import os

OUTPUT_PATH = os.path.join("docs", "LexisNexis_LOI_Draft.pdf")

lines = [
    "CONFIDENTIAL - LETTER OF INTENT",
    "",
    "To: Board of Directors, LexiPro Forensic OS",
    "From: Corporate Development, LexisNexis",
    "Subject: Acquisition Offer",
    "",
    "We are pleased to submit this non-binding Letter of Intent to acquire all outstanding equity of LexiPro Forensic OS.",
    "",
    "Proposed Purchase Price: $55,000,000 USD (Fifty-Five Million Dollars), payable in cash and stock.",
    "",
    "This offer is contingent upon successful technical diligence regarding the Immutable Log Shipping and Optical Verification protocols.",
    "",
    "Generated by LexiPro Auto-Draft // Cryptographically Signed"
]


def main():
    os.makedirs(os.path.dirname(OUTPUT_PATH), exist_ok=True)
    c = canvas.Canvas(OUTPUT_PATH, pagesize=letter)
    width, height = letter
    margin = 0.85 * inch
    y = height - margin

    c.setFont("Helvetica-Bold", 16)
    c.drawString(margin, y, lines[0])
    y -= 0.4 * inch

    c.setFont("Helvetica", 11)
    for line in lines[1:]:
        if line == "":
            y -= 0.18 * inch
            continue
        c.drawString(margin, y, line)
        y -= 0.22 * inch

    c.showPage()
    c.save()
    print(f"[LOI] Generated {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
